apiVersion: v1
kind: ConfigMap
metadata:
  name: config-timer
  namespace: vanus
data:
  timer.yaml: |-
    name: "timer"
    ip: ${POD_IP}
    etcd:
      - vanus-controller-0.vanus-controller:2379
      - vanus-controller-1.vanus-controller:2379
      - vanus-controller-2.vanus-controller:2379
    metadata:
      key_prefix: "/vanus"
    leaderelection:
      lease_duration: 15
    timingwheel:
      tick: 1
      wheel_size: 32
      layers: 4
    controllers:
      - vanus-controller-0.vanus-controller.vanus.svc:2048
      - vanus-controller-1.vanus-controller.vanus.svc:2048
      - vanus-controller-2.vanus-controller.vanus.svc:2048
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanus-timer
  namespace: vanus
  labels:
    app: vanus-timer
spec:
  selector:
    matchLabels:
      app: vanus-timer
  replicas: 2
  template:
    metadata:
      labels:
        app: vanus-timer
      annotations:
        vanus.dev/metrics.port: "2112"
    spec:
      containers:
        - name: timer
          image: public.ecr.aws/vanus/timer:v0.3.0
          imagePullPolicy: IfNotPresent
          env:
            - name: VANUS_LOG_LEVEL
              value: DEBUG
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: config-timer
              mountPath: /vanus/config
      volumes:
        - name: config-timer
          configMap:
            name: config-timer
