apiVersion: v1
data:
  timer.yaml: |-
    name: "timer"
    ip: ${POD_IP}
    etcd:
      - vanus-etcd-0.vanus-etcd:2379
      - vanus-etcd-1.vanus-etcd:2379
      - vanus-etcd-2.vanus-etcd:2379
    leader_election:
      lease_duration: 15
    timingwheel:
      tick: 1
      wheel_size: 32
      layers: 4
    controllers:
      - vanus-controller-0.vanus-controller.vanus-standby.svc:2048
      - vanus-controller-1.vanus-controller.vanus-standby.svc:2048
kind: ConfigMap
metadata:
  name: config-timer
  namespace: vanus-standby
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vanus-timer
  name: vanus-timer
  namespace: vanus-standby
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vanus-timer
  template:
    metadata:
      annotations:
        vanus.dev/metrics.port: "2112"
      labels:
        app: vanus-timer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: core.standby.vanus.ai/dedicated
                operator: In
                values:
                - cluster
      tolerations:
      - key: "core.standby.vanus.ai/dedicated"
        operator: "Equal"
        value: "cluster"
        effect: "NoSchedule"
      containers:
      - env:
        - name: VANUS_LOG_LEVEL
          value: INFO
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: public.ecr.aws/vanus/timer:v0.9.0
        imagePullPolicy: IfNotPresent
        name: timer
        volumeMounts:
        - mountPath: /vanus/config
          name: config-timer
      volumes:
      - configMap:
          name: config-timer
        name: config-timer
